// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: room_agent/v1/summary.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomSummaryAgent_RunSummary_FullMethodName         = "/room_agent.v1.RoomSummaryAgent/RunSummary"
	RoomSummaryAgent_ResumeSummaryState_FullMethodName = "/room_agent.v1.RoomSummaryAgent/ResumeSummaryState"
)

// RoomSummaryAgentClient is the client API for RoomSummaryAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomSummaryAgentClient interface {
	RunSummary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error)
	ResumeSummaryState(ctx context.Context, in *ResumeSummaryStateRequest, opts ...grpc.CallOption) (*SummaryResponse, error)
}

type roomSummaryAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomSummaryAgentClient(cc grpc.ClientConnInterface) RoomSummaryAgentClient {
	return &roomSummaryAgentClient{cc}
}

func (c *roomSummaryAgentClient) RunSummary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryResponse)
	err := c.cc.Invoke(ctx, RoomSummaryAgent_RunSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomSummaryAgentClient) ResumeSummaryState(ctx context.Context, in *ResumeSummaryStateRequest, opts ...grpc.CallOption) (*SummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummaryResponse)
	err := c.cc.Invoke(ctx, RoomSummaryAgent_ResumeSummaryState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomSummaryAgentServer is the server API for RoomSummaryAgent service.
// All implementations must embed UnimplementedRoomSummaryAgentServer
// for forward compatibility.
type RoomSummaryAgentServer interface {
	RunSummary(context.Context, *SummaryRequest) (*SummaryResponse, error)
	ResumeSummaryState(context.Context, *ResumeSummaryStateRequest) (*SummaryResponse, error)
	mustEmbedUnimplementedRoomSummaryAgentServer()
}

// UnimplementedRoomSummaryAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomSummaryAgentServer struct{}

func (UnimplementedRoomSummaryAgentServer) RunSummary(context.Context, *SummaryRequest) (*SummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunSummary not implemented")
}
func (UnimplementedRoomSummaryAgentServer) ResumeSummaryState(context.Context, *ResumeSummaryStateRequest) (*SummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSummaryState not implemented")
}
func (UnimplementedRoomSummaryAgentServer) mustEmbedUnimplementedRoomSummaryAgentServer() {}
func (UnimplementedRoomSummaryAgentServer) testEmbeddedByValue()                          {}

// UnsafeRoomSummaryAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomSummaryAgentServer will
// result in compilation errors.
type UnsafeRoomSummaryAgentServer interface {
	mustEmbedUnimplementedRoomSummaryAgentServer()
}

func RegisterRoomSummaryAgentServer(s grpc.ServiceRegistrar, srv RoomSummaryAgentServer) {
	// If the following call panics, it indicates UnimplementedRoomSummaryAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomSummaryAgent_ServiceDesc, srv)
}

func _RoomSummaryAgent_RunSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomSummaryAgentServer).RunSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomSummaryAgent_RunSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomSummaryAgentServer).RunSummary(ctx, req.(*SummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomSummaryAgent_ResumeSummaryState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeSummaryStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomSummaryAgentServer).ResumeSummaryState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomSummaryAgent_ResumeSummaryState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomSummaryAgentServer).ResumeSummaryState(ctx, req.(*ResumeSummaryStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomSummaryAgent_ServiceDesc is the grpc.ServiceDesc for RoomSummaryAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomSummaryAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "room_agent.v1.RoomSummaryAgent",
	HandlerType: (*RoomSummaryAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunSummary",
			Handler:    _RoomSummaryAgent_RunSummary_Handler,
		},
		{
			MethodName: "ResumeSummaryState",
			Handler:    _RoomSummaryAgent_ResumeSummaryState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "room_agent/v1/summary.proto",
}
