// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: room_agent/v1/summary.proto

package agentpb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SummaryAction int32

const (
	SummaryAction_SUMMARY_ACTION_UNSPECIFIED SummaryAction = 0
	SummaryAction_SUMMARY_ACTION_START       SummaryAction = 1
	SummaryAction_SUMMARY_ACTION_RETRY       SummaryAction = 2
	SummaryAction_SUMMARY_ACTION_CANCEL      SummaryAction = 3
)

// Enum value maps for SummaryAction.
var (
	SummaryAction_name = map[int32]string{
		0: "SUMMARY_ACTION_UNSPECIFIED",
		1: "SUMMARY_ACTION_START",
		2: "SUMMARY_ACTION_RETRY",
		3: "SUMMARY_ACTION_CANCEL",
	}
	SummaryAction_value = map[string]int32{
		"SUMMARY_ACTION_UNSPECIFIED": 0,
		"SUMMARY_ACTION_START":       1,
		"SUMMARY_ACTION_RETRY":       2,
		"SUMMARY_ACTION_CANCEL":      3,
	}
)

func (x SummaryAction) Enum() *SummaryAction {
	p := new(SummaryAction)
	*p = x
	return p
}

func (x SummaryAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SummaryAction) Descriptor() protoreflect.EnumDescriptor {
	return file_room_agent_v1_summary_proto_enumTypes[0].Descriptor()
}

func (SummaryAction) Type() protoreflect.EnumType {
	return &file_room_agent_v1_summary_proto_enumTypes[0]
}

func (x SummaryAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SummaryAction.Descriptor instead.
func (SummaryAction) EnumDescriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{0}
}

type InterruptAction int32

const (
	InterruptAction_INTERRUPT_ACTION_UNSPECIFIED InterruptAction = 0
	InterruptAction_INTERRUPT_ACTION_RETRY       InterruptAction = 1
	InterruptAction_INTERRUPT_ACTION_CANCEL      InterruptAction = 2
)

// Enum value maps for InterruptAction.
var (
	InterruptAction_name = map[int32]string{
		0: "INTERRUPT_ACTION_UNSPECIFIED",
		1: "INTERRUPT_ACTION_RETRY",
		2: "INTERRUPT_ACTION_CANCEL",
	}
	InterruptAction_value = map[string]int32{
		"INTERRUPT_ACTION_UNSPECIFIED": 0,
		"INTERRUPT_ACTION_RETRY":       1,
		"INTERRUPT_ACTION_CANCEL":      2,
	}
)

func (x InterruptAction) Enum() *InterruptAction {
	p := new(InterruptAction)
	*p = x
	return p
}

func (x InterruptAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterruptAction) Descriptor() protoreflect.EnumDescriptor {
	return file_room_agent_v1_summary_proto_enumTypes[1].Descriptor()
}

func (InterruptAction) Type() protoreflect.EnumType {
	return &file_room_agent_v1_summary_proto_enumTypes[1]
}

func (x InterruptAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterruptAction.Descriptor instead.
func (InterruptAction) EnumDescriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{1}
}

type SummaryStatus int32

const (
	SummaryStatus_SUMMARY_STATUS_UNSPECIFIED           SummaryStatus = 0
	SummaryStatus_SUMMARY_STATUS_SUCCEEDED             SummaryStatus = 1
	SummaryStatus_SUMMARY_STATUS_FAILED                SummaryStatus = 2
	SummaryStatus_SUMMARY_STATUS_WAITING_USER_DECISION SummaryStatus = 3
)

// Enum value maps for SummaryStatus.
var (
	SummaryStatus_name = map[int32]string{
		0: "SUMMARY_STATUS_UNSPECIFIED",
		1: "SUMMARY_STATUS_SUCCEEDED",
		2: "SUMMARY_STATUS_FAILED",
		3: "SUMMARY_STATUS_WAITING_USER_DECISION",
	}
	SummaryStatus_value = map[string]int32{
		"SUMMARY_STATUS_UNSPECIFIED":           0,
		"SUMMARY_STATUS_SUCCEEDED":             1,
		"SUMMARY_STATUS_FAILED":                2,
		"SUMMARY_STATUS_WAITING_USER_DECISION": 3,
	}
)

func (x SummaryStatus) Enum() *SummaryStatus {
	p := new(SummaryStatus)
	*p = x
	return p
}

func (x SummaryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SummaryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_agent_v1_summary_proto_enumTypes[2].Descriptor()
}

func (SummaryStatus) Type() protoreflect.EnumType {
	return &file_room_agent_v1_summary_proto_enumTypes[2]
}

func (x SummaryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SummaryStatus.Descriptor instead.
func (SummaryStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{2}
}

type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_room_agent_v1_summary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_room_agent_v1_summary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Scope) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SummaryRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RequestId    string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SummaryRunId string                 `protobuf:"bytes,2,opt,name=summary_run_id,json=summaryRunId,proto3" json:"summary_run_id,omitempty"`
	Scope        *Scope                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Action       SummaryAction          `protobuf:"varint,4,opt,name=action,proto3,enum=room_agent.v1.SummaryAction" json:"action,omitempty"`
	// 只有 SUMMARY_ACTION_START 时传入。
	RoomMessages  []*RoomMessage `protobuf:"bytes,5,rep,name=room_messages,json=roomMessages,proto3" json:"room_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_room_agent_v1_summary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_agent_v1_summary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{1}
}

func (x *SummaryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SummaryRequest) GetSummaryRunId() string {
	if x != nil {
		return x.SummaryRunId
	}
	return ""
}

func (x *SummaryRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SummaryRequest) GetAction() SummaryAction {
	if x != nil {
		return x.Action
	}
	return SummaryAction_SUMMARY_ACTION_UNSPECIFIED
}

func (x *SummaryRequest) GetRoomMessages() []*RoomMessage {
	if x != nil {
		return x.RoomMessages
	}
	return nil
}

type ResumeSummaryStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SummaryRunId  string                 `protobuf:"bytes,2,opt,name=summary_run_id,json=summaryRunId,proto3" json:"summary_run_id,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSummaryStateRequest) Reset() {
	*x = ResumeSummaryStateRequest{}
	mi := &file_room_agent_v1_summary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSummaryStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSummaryStateRequest) ProtoMessage() {}

func (x *ResumeSummaryStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_agent_v1_summary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSummaryStateRequest.ProtoReflect.Descriptor instead.
func (*ResumeSummaryStateRequest) Descriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeSummaryStateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResumeSummaryStateRequest) GetSummaryRunId() string {
	if x != nil {
		return x.SummaryRunId
	}
	return ""
}

func (x *ResumeSummaryStateRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type RoomMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Seq           int64                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	SendTime      *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMessage) Reset() {
	*x = RoomMessage{}
	mi := &file_room_agent_v1_summary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMessage) ProtoMessage() {}

func (x *RoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_room_agent_v1_summary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMessage.ProtoReflect.Descriptor instead.
func (*RoomMessage) Descriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{3}
}

func (x *RoomMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RoomMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *RoomMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RoomMessage) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RoomMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RoomMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoomMessage) GetSendTime() *timestamp.Timestamp {
	if x != nil {
		return x.SendTime
	}
	return nil
}

type SummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SummaryRunId  string                 `protobuf:"bytes,2,opt,name=summary_run_id,json=summaryRunId,proto3" json:"summary_run_id,omitempty"`
	Status        SummaryStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=room_agent.v1.SummaryStatus" json:"status,omitempty"`
	Summary       *SummaryOutput         `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Error         *ErrorInfo             `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	RetryRequired *RetryRequired         `protobuf:"bytes,6,opt,name=retry_required,json=retryRequired,proto3" json:"retry_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_room_agent_v1_summary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_agent_v1_summary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{4}
}

func (x *SummaryResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SummaryResponse) GetSummaryRunId() string {
	if x != nil {
		return x.SummaryRunId
	}
	return ""
}

func (x *SummaryResponse) GetStatus() SummaryStatus {
	if x != nil {
		return x.Status
	}
	return SummaryStatus_SUMMARY_STATUS_UNSPECIFIED
}

func (x *SummaryResponse) GetSummary() *SummaryOutput {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *SummaryResponse) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SummaryResponse) GetRetryRequired() *RetryRequired {
	if x != nil {
		return x.RetryRequired
	}
	return nil
}

type SummarySegment struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SummaryContentSegment string                 `protobuf:"bytes,1,opt,name=summary_content_segment,json=summaryContentSegment,proto3" json:"summary_content_segment,omitempty"`
	Citations             []*Citation            `protobuf:"bytes,2,rep,name=citations,proto3" json:"citations,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SummarySegment) Reset() {
	*x = SummarySegment{}
	mi := &file_room_agent_v1_summary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarySegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarySegment) ProtoMessage() {}

func (x *SummarySegment) ProtoReflect() protoreflect.Message {
	mi := &file_room_agent_v1_summary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarySegment.ProtoReflect.Descriptor instead.
func (*SummarySegment) Descriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{5}
}

func (x *SummarySegment) GetSummaryContentSegment() string {
	if x != nil {
		return x.SummaryContentSegment
	}
	return ""
}

func (x *SummarySegment) GetCitations() []*Citation {
	if x != nil {
		return x.Citations
	}
	return nil
}

type Citation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_room_agent_v1_summary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_room_agent_v1_summary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{6}
}

func (x *Citation) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Citation) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type SummaryOutput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SummaryContent []*SummarySegment      `protobuf:"bytes,1,rep,name=summary_content,json=summaryContent,proto3" json:"summary_content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SummaryOutput) Reset() {
	*x = SummaryOutput{}
	mi := &file_room_agent_v1_summary_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryOutput) ProtoMessage() {}

func (x *SummaryOutput) ProtoReflect() protoreflect.Message {
	mi := &file_room_agent_v1_summary_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryOutput.ProtoReflect.Descriptor instead.
func (*SummaryOutput) Descriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{7}
}

func (x *SummaryOutput) GetSummaryContent() []*SummarySegment {
	if x != nil {
		return x.SummaryContent
	}
	return nil
}

type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_room_agent_v1_summary_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_room_agent_v1_summary_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RetryRequired struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReasonCode       string                 `protobuf:"bytes,1,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ValidationIssues []string               `protobuf:"bytes,2,rep,name=validation_issues,json=validationIssues,proto3" json:"validation_issues,omitempty"`
	ReflectionIssues []string               `protobuf:"bytes,3,rep,name=reflection_issues,json=reflectionIssues,proto3" json:"reflection_issues,omitempty"`
	RepairCount      int32                  `protobuf:"varint,4,opt,name=repair_count,json=repairCount,proto3" json:"repair_count,omitempty"`
	MaxRepairCount   int32                  `protobuf:"varint,5,opt,name=max_repair_count,json=maxRepairCount,proto3" json:"max_repair_count,omitempty"`
	AllowedActions   []InterruptAction      `protobuf:"varint,6,rep,packed,name=allowed_actions,json=allowedActions,proto3,enum=room_agent.v1.InterruptAction" json:"allowed_actions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RetryRequired) Reset() {
	*x = RetryRequired{}
	mi := &file_room_agent_v1_summary_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryRequired) ProtoMessage() {}

func (x *RetryRequired) ProtoReflect() protoreflect.Message {
	mi := &file_room_agent_v1_summary_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryRequired.ProtoReflect.Descriptor instead.
func (*RetryRequired) Descriptor() ([]byte, []int) {
	return file_room_agent_v1_summary_proto_rawDescGZIP(), []int{9}
}

func (x *RetryRequired) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *RetryRequired) GetValidationIssues() []string {
	if x != nil {
		return x.ValidationIssues
	}
	return nil
}

func (x *RetryRequired) GetReflectionIssues() []string {
	if x != nil {
		return x.ReflectionIssues
	}
	return nil
}

func (x *RetryRequired) GetRepairCount() int32 {
	if x != nil {
		return x.RepairCount
	}
	return 0
}

func (x *RetryRequired) GetMaxRepairCount() int32 {
	if x != nil {
		return x.MaxRepairCount
	}
	return 0
}

func (x *RetryRequired) GetAllowedActions() []InterruptAction {
	if x != nil {
		return x.AllowedActions
	}
	return nil
}

var File_room_agent_v1_summary_proto protoreflect.FileDescriptor

const file_room_agent_v1_summary_proto_rawDesc = "" +
	"\n" +
	"\x1broom_agent/v1/summary.proto\x12\rroom_agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x05Scope\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xf8\x01\n" +
	"\x0eSummaryRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12$\n" +
	"\x0esummary_run_id\x18\x02 \x01(\tR\fsummaryRunId\x12*\n" +
	"\x05scope\x18\x03 \x01(\v2\x14.room_agent.v1.ScopeR\x05scope\x124\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1c.room_agent.v1.SummaryActionR\x06action\x12?\n" +
	"\rroom_messages\x18\x05 \x03(\v2\x1a.room_agent.v1.RoomMessageR\froomMessages\"\x8c\x01\n" +
	"\x19ResumeSummaryStateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12$\n" +
	"\x0esummary_run_id\x18\x02 \x01(\tR\fsummaryRunId\x12*\n" +
	"\x05scope\x18\x03 \x01(\v2\x14.room_agent.v1.ScopeR\x05scope\"\xf3\x01\n" +
	"\vRoomMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x127\n" +
	"\tsend_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bsendTime\"\xb9\x02\n" +
	"\x0fSummaryResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12$\n" +
	"\x0esummary_run_id\x18\x02 \x01(\tR\fsummaryRunId\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.room_agent.v1.SummaryStatusR\x06status\x126\n" +
	"\asummary\x18\x04 \x01(\v2\x1c.room_agent.v1.SummaryOutputR\asummary\x12.\n" +
	"\x05error\x18\x05 \x01(\v2\x18.room_agent.v1.ErrorInfoR\x05error\x12C\n" +
	"\x0eretry_required\x18\x06 \x01(\v2\x1c.room_agent.v1.RetryRequiredR\rretryRequired\"\x7f\n" +
	"\x0eSummarySegment\x126\n" +
	"\x17summary_content_segment\x18\x01 \x01(\tR\x15summaryContentSegment\x125\n" +
	"\tcitations\x18\x02 \x03(\v2\x17.room_agent.v1.CitationR\tcitations\";\n" +
	"\bCitation\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\"W\n" +
	"\rSummaryOutput\x12F\n" +
	"\x0fsummary_content\x18\x01 \x03(\v2\x1d.room_agent.v1.SummarySegmentR\x0esummaryContent\"9\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa0\x02\n" +
	"\rRetryRequired\x12\x1f\n" +
	"\vreason_code\x18\x01 \x01(\tR\n" +
	"reasonCode\x12+\n" +
	"\x11validation_issues\x18\x02 \x03(\tR\x10validationIssues\x12+\n" +
	"\x11reflection_issues\x18\x03 \x03(\tR\x10reflectionIssues\x12!\n" +
	"\frepair_count\x18\x04 \x01(\x05R\vrepairCount\x12(\n" +
	"\x10max_repair_count\x18\x05 \x01(\x05R\x0emaxRepairCount\x12G\n" +
	"\x0fallowed_actions\x18\x06 \x03(\x0e2\x1e.room_agent.v1.InterruptActionR\x0eallowedActions*~\n" +
	"\rSummaryAction\x12\x1e\n" +
	"\x1aSUMMARY_ACTION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SUMMARY_ACTION_START\x10\x01\x12\x18\n" +
	"\x14SUMMARY_ACTION_RETRY\x10\x02\x12\x19\n" +
	"\x15SUMMARY_ACTION_CANCEL\x10\x03*l\n" +
	"\x0fInterruptAction\x12 \n" +
	"\x1cINTERRUPT_ACTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16INTERRUPT_ACTION_RETRY\x10\x01\x12\x1b\n" +
	"\x17INTERRUPT_ACTION_CANCEL\x10\x02*\x92\x01\n" +
	"\rSummaryStatus\x12\x1e\n" +
	"\x1aSUMMARY_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SUMMARY_STATUS_SUCCEEDED\x10\x01\x12\x19\n" +
	"\x15SUMMARY_STATUS_FAILED\x10\x02\x12(\n" +
	"$SUMMARY_STATUS_WAITING_USER_DECISION\x10\x032\xbf\x01\n" +
	"\x10RoomSummaryAgent\x12K\n" +
	"\n" +
	"RunSummary\x12\x1d.room_agent.v1.SummaryRequest\x1a\x1e.room_agent.v1.SummaryResponse\x12^\n" +
	"\x12ResumeSummaryState\x12(.room_agent.v1.ResumeSummaryStateRequest\x1a\x1e.room_agent.v1.SummaryResponseB\"Z IM_backend/room_agent/v1;agentpbb\x06proto3"

var (
	file_room_agent_v1_summary_proto_rawDescOnce sync.Once
	file_room_agent_v1_summary_proto_rawDescData []byte
)

func file_room_agent_v1_summary_proto_rawDescGZIP() []byte {
	file_room_agent_v1_summary_proto_rawDescOnce.Do(func() {
		file_room_agent_v1_summary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_agent_v1_summary_proto_rawDesc), len(file_room_agent_v1_summary_proto_rawDesc)))
	})
	return file_room_agent_v1_summary_proto_rawDescData
}

var file_room_agent_v1_summary_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_room_agent_v1_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_room_agent_v1_summary_proto_goTypes = []any{
	(SummaryAction)(0),                // 0: room_agent.v1.SummaryAction
	(InterruptAction)(0),              // 1: room_agent.v1.InterruptAction
	(SummaryStatus)(0),                // 2: room_agent.v1.SummaryStatus
	(*Scope)(nil),                     // 3: room_agent.v1.Scope
	(*SummaryRequest)(nil),            // 4: room_agent.v1.SummaryRequest
	(*ResumeSummaryStateRequest)(nil), // 5: room_agent.v1.ResumeSummaryStateRequest
	(*RoomMessage)(nil),               // 6: room_agent.v1.RoomMessage
	(*SummaryResponse)(nil),           // 7: room_agent.v1.SummaryResponse
	(*SummarySegment)(nil),            // 8: room_agent.v1.SummarySegment
	(*Citation)(nil),                  // 9: room_agent.v1.Citation
	(*SummaryOutput)(nil),             // 10: room_agent.v1.SummaryOutput
	(*ErrorInfo)(nil),                 // 11: room_agent.v1.ErrorInfo
	(*RetryRequired)(nil),             // 12: room_agent.v1.RetryRequired
	(*timestamp.Timestamp)(nil),       // 13: google.protobuf.Timestamp
}
var file_room_agent_v1_summary_proto_depIdxs = []int32{
	3,  // 0: room_agent.v1.SummaryRequest.scope:type_name -> room_agent.v1.Scope
	0,  // 1: room_agent.v1.SummaryRequest.action:type_name -> room_agent.v1.SummaryAction
	6,  // 2: room_agent.v1.SummaryRequest.room_messages:type_name -> room_agent.v1.RoomMessage
	3,  // 3: room_agent.v1.ResumeSummaryStateRequest.scope:type_name -> room_agent.v1.Scope
	13, // 4: room_agent.v1.RoomMessage.send_time:type_name -> google.protobuf.Timestamp
	2,  // 5: room_agent.v1.SummaryResponse.status:type_name -> room_agent.v1.SummaryStatus
	10, // 6: room_agent.v1.SummaryResponse.summary:type_name -> room_agent.v1.SummaryOutput
	11, // 7: room_agent.v1.SummaryResponse.error:type_name -> room_agent.v1.ErrorInfo
	12, // 8: room_agent.v1.SummaryResponse.retry_required:type_name -> room_agent.v1.RetryRequired
	9,  // 9: room_agent.v1.SummarySegment.citations:type_name -> room_agent.v1.Citation
	8,  // 10: room_agent.v1.SummaryOutput.summary_content:type_name -> room_agent.v1.SummarySegment
	1,  // 11: room_agent.v1.RetryRequired.allowed_actions:type_name -> room_agent.v1.InterruptAction
	4,  // 12: room_agent.v1.RoomSummaryAgent.RunSummary:input_type -> room_agent.v1.SummaryRequest
	5,  // 13: room_agent.v1.RoomSummaryAgent.ResumeSummaryState:input_type -> room_agent.v1.ResumeSummaryStateRequest
	7,  // 14: room_agent.v1.RoomSummaryAgent.RunSummary:output_type -> room_agent.v1.SummaryResponse
	7,  // 15: room_agent.v1.RoomSummaryAgent.ResumeSummaryState:output_type -> room_agent.v1.SummaryResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_room_agent_v1_summary_proto_init() }
func file_room_agent_v1_summary_proto_init() {
	if File_room_agent_v1_summary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_agent_v1_summary_proto_rawDesc), len(file_room_agent_v1_summary_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_agent_v1_summary_proto_goTypes,
		DependencyIndexes: file_room_agent_v1_summary_proto_depIdxs,
		EnumInfos:         file_room_agent_v1_summary_proto_enumTypes,
		MessageInfos:      file_room_agent_v1_summary_proto_msgTypes,
	}.Build()
	File_room_agent_v1_summary_proto = out.File
	file_room_agent_v1_summary_proto_goTypes = nil
	file_room_agent_v1_summary_proto_depIdxs = nil
}
