// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: ws.proto

package wspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WsFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsFrame) Reset() {
	*x = WsFrame{}
	mi := &file_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsFrame) ProtoMessage() {}

func (x *WsFrame) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsFrame.ProtoReflect.Descriptor instead.
func (*WsFrame) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{0}
}

func (x *WsFrame) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *WsFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*WsFrame             `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsBatch) Reset() {
	*x = WsBatch{}
	mi := &file_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsBatch) ProtoMessage() {}

func (x *WsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsBatch.ProtoReflect.Descriptor instead.
func (*WsBatch) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{1}
}

func (x *WsBatch) GetFrames() []*WsFrame {
	if x != nil {
		return x.Frames
	}
	return nil
}

type MessageReadAckReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastReadSeq    int64                  `protobuf:"varint,2,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageReadAckReq) Reset() {
	*x = MessageReadAckReq{}
	mi := &file_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReadAckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReadAckReq) ProtoMessage() {}

func (x *MessageReadAckReq) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReadAckReq.ProtoReflect.Descriptor instead.
func (*MessageReadAckReq) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{2}
}

func (x *MessageReadAckReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageReadAckReq) GetLastReadSeq() int64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

type MessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId   string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	RecvId        string                 `protobuf:"bytes,2,opt,name=recv_id,json=recvId,proto3" json:"recv_id,omitempty"`
	ConvType      int32                  `protobuf:"varint,3,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`
	CType         int32                  `protobuf:"varint,4,opt,name=c_type,json=cType,proto3" json:"c_type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	VideoTime     int64                  `protobuf:"varint,6,opt,name=video_time,json=videoTime,proto3" json:"video_time,omitempty"`
	HasVideoTime  bool                   `protobuf:"varint,7,opt,name=has_video_time,json=hasVideoTime,proto3" json:"has_video_time,omitempty"`
	FileId        string                 `protobuf:"bytes,10,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	StickerId     string                 `protobuf:"bytes,17,opt,name=sticker_id,json=stickerId,proto3" json:"sticker_id,omitempty"`
	PackId        string                 `protobuf:"bytes,18,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReq) Reset() {
	*x = MessageReq{}
	mi := &file_ws_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReq) ProtoMessage() {}

func (x *MessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReq.ProtoReflect.Descriptor instead.
func (*MessageReq) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{3}
}

func (x *MessageReq) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessageReq) GetRecvId() string {
	if x != nil {
		return x.RecvId
	}
	return ""
}

func (x *MessageReq) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *MessageReq) GetCType() int32 {
	if x != nil {
		return x.CType
	}
	return 0
}

func (x *MessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageReq) GetVideoTime() int64 {
	if x != nil {
		return x.VideoTime
	}
	return 0
}

func (x *MessageReq) GetHasVideoTime() bool {
	if x != nil {
		return x.HasVideoTime
	}
	return false
}

func (x *MessageReq) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *MessageReq) GetStickerId() string {
	if x != nil {
		return x.StickerId
	}
	return ""
}

func (x *MessageReq) GetPackId() string {
	if x != nil {
		return x.PackId
	}
	return ""
}

type MessageAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId    string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Extra          string                 `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	SendTime       int64                  `protobuf:"varint,5,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	ConversationId string                 `protobuf:"bytes,6,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            int64                  `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	AttachmentId   string                 `protobuf:"bytes,8,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_ws_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{4}
}

func (x *MessageAck) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessageAck) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MessageAck) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *MessageAck) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *MessageAck) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageAck) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageAck) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

type RoomMessageNotice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Seq            int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomMessageNotice) Reset() {
	*x = RoomMessageNotice{}
	mi := &file_ws_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMessageNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMessageNotice) ProtoMessage() {}

func (x *RoomMessageNotice) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMessageNotice.ProtoReflect.Descriptor instead.
func (*RoomMessageNotice) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{5}
}

func (x *RoomMessageNotice) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RoomMessageNotice) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RoomMessageNotice) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type MessageReadAckEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastReadSeq    int64                  `protobuf:"varint,3,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	ConvType       int32                  `protobuf:"varint,4,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`
	SenderId       string                 `protobuf:"bytes,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Avatar         string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageReadAckEvent) Reset() {
	*x = MessageReadAckEvent{}
	mi := &file_ws_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReadAckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReadAckEvent) ProtoMessage() {}

func (x *MessageReadAckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReadAckEvent.ProtoReflect.Descriptor instead.
func (*MessageReadAckEvent) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{6}
}

func (x *MessageReadAckEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MessageReadAckEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageReadAckEvent) GetLastReadSeq() int64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

func (x *MessageReadAckEvent) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *MessageReadAckEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageReadAckEvent) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type MessageEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Seq            int64                  `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	CType          int32                  `protobuf:"varint,7,opt,name=c_type,json=cType,proto3" json:"c_type,omitempty"`
	Content        string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	SendTime       int64                  `protobuf:"varint,9,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	ClientMsgId    string                 `protobuf:"bytes,11,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	VideoId        string                 `protobuf:"bytes,12,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VideoTime      *int64                 `protobuf:"varint,13,opt,name=video_time,json=videoTime,proto3,oneof" json:"video_time,omitempty"`
	Status         int32                  `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	AttachmentId   string                 `protobuf:"bytes,25,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_ws_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{7}
}

func (x *MessageEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageEvent) GetCType() int32 {
	if x != nil {
		return x.CType
	}
	return 0
}

func (x *MessageEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageEvent) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *MessageEvent) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessageEvent) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *MessageEvent) GetVideoTime() int64 {
	if x != nil && x.VideoTime != nil {
		return *x.VideoTime
	}
	return 0
}

func (x *MessageEvent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MessageEvent) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

var File_ws_proto protoreflect.FileDescriptor

const file_ws_proto_rawDesc = "" +
	"\n" +
	"\bws.proto\x12\x05im.ws\"-\n" +
	"\aWsFrame\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"1\n" +
	"\aWsBatch\x12&\n" +
	"\x06frames\x18\x01 \x03(\v2\x0e.im.ws.WsFrameR\x06frames\"`\n" +
	"\x11MessageReadAckReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\rlast_read_seq\x18\x02 \x01(\x03R\vlastReadSeq\"\xad\x02\n" +
	"\n" +
	"MessageReq\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12\x17\n" +
	"\arecv_id\x18\x02 \x01(\tR\x06recvId\x12\x1b\n" +
	"\tconv_type\x18\x03 \x01(\x05R\bconvType\x12\x15\n" +
	"\x06c_type\x18\x04 \x01(\x05R\x05cType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"video_time\x18\x06 \x01(\x03R\tvideoTime\x12$\n" +
	"\x0ehas_video_time\x18\a \x01(\bR\fhasVideoTime\x12\x17\n" +
	"\afile_id\x18\n" +
	" \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"sticker_id\x18\x11 \x01(\tR\tstickerId\x12\x17\n" +
	"\apack_id\x18\x12 \x01(\tR\x06packId\"\xfa\x01\n" +
	"\n" +
	"MessageAck\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05extra\x18\x04 \x01(\tR\x05extra\x12\x1b\n" +
	"\tsend_time\x18\x05 \x01(\x03R\bsendTime\x12'\n" +
	"\x0fconversation_id\x18\x06 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\a \x01(\x03R\x03seq\x12#\n" +
	"\rattachment_id\x18\b \x01(\tR\fattachmentId\"m\n" +
	"\x11RoomMessageNotice\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\"\xcd\x01\n" +
	"\x13MessageReadAckEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\"\n" +
	"\rlast_read_seq\x18\x03 \x01(\x03R\vlastReadSeq\x12\x1b\n" +
	"\tconv_type\x18\x04 \x01(\x05R\bconvType\x12\x1b\n" +
	"\tsender_id\x18\x05 \x01(\tR\bsenderId\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\"\x9a\x03\n" +
	"\fMessageEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x03R\x03seq\x12\x15\n" +
	"\x06c_type\x18\a \x01(\x05R\x05cType\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1b\n" +
	"\tsend_time\x18\t \x01(\x03R\bsendTime\x12\"\n" +
	"\rclient_msg_id\x18\v \x01(\tR\vclientMsgId\x12\x19\n" +
	"\bvideo_id\x18\f \x01(\tR\avideoId\x12\"\n" +
	"\n" +
	"video_time\x18\r \x01(\x03H\x00R\tvideoTime\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x0e \x01(\x05R\x06status\x12#\n" +
	"\rattachment_id\x18\x19 \x01(\tR\fattachmentIdB\r\n" +
	"\v_video_timeJ\x04\b\x04\x10\x05J\x04\b\x06\x10\aJ\x04\b\n" +
	"\x10\vJ\x04\b\x12\x10\x19B*Z(IM_backend/internal/transport/ws/pb;wspbb\x06proto3"

var (
	file_ws_proto_rawDescOnce sync.Once
	file_ws_proto_rawDescData []byte
)

func file_ws_proto_rawDescGZIP() []byte {
	file_ws_proto_rawDescOnce.Do(func() {
		file_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)))
	})
	return file_ws_proto_rawDescData
}

var file_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ws_proto_goTypes = []any{
	(*WsFrame)(nil),             // 0: im.ws.WsFrame
	(*WsBatch)(nil),             // 1: im.ws.WsBatch
	(*MessageReadAckReq)(nil),   // 2: im.ws.MessageReadAckReq
	(*MessageReq)(nil),          // 3: im.ws.MessageReq
	(*MessageAck)(nil),          // 4: im.ws.MessageAck
	(*RoomMessageNotice)(nil),   // 5: im.ws.RoomMessageNotice
	(*MessageReadAckEvent)(nil), // 6: im.ws.MessageReadAckEvent
	(*MessageEvent)(nil),        // 7: im.ws.MessageEvent
}
var file_ws_proto_depIdxs = []int32{
	0, // 0: im.ws.WsBatch.frames:type_name -> im.ws.WsFrame
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ws_proto_init() }
func file_ws_proto_init() {
	if File_ws_proto != nil {
		return
	}
	file_ws_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_proto_goTypes,
		DependencyIndexes: file_ws_proto_depIdxs,
		MessageInfos:      file_ws_proto_msgTypes,
	}.Build()
	File_ws_proto = out.File
	file_ws_proto_goTypes = nil
	file_ws_proto_depIdxs = nil
}
