// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: ws.proto

package wspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WsFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsFrame) Reset() {
	*x = WsFrame{}
	mi := &file_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsFrame) ProtoMessage() {}

func (x *WsFrame) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsFrame.ProtoReflect.Descriptor instead.
func (*WsFrame) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{0}
}

func (x *WsFrame) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *WsFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MessageReadAckReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastReadSeq    int64                  `protobuf:"varint,2,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageReadAckReq) Reset() {
	*x = MessageReadAckReq{}
	mi := &file_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReadAckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReadAckReq) ProtoMessage() {}

func (x *MessageReadAckReq) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReadAckReq.ProtoReflect.Descriptor instead.
func (*MessageReadAckReq) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{1}
}

func (x *MessageReadAckReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageReadAckReq) GetLastReadSeq() int64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

func (x *MessageReadAckReq) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type MessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId   string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	RecvId        string                 `protobuf:"bytes,2,opt,name=recv_id,json=recvId,proto3" json:"recv_id,omitempty"`
	ConvType      int32                  `protobuf:"varint,3,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`
	CType         int32                  `protobuf:"varint,4,opt,name=c_type,json=cType,proto3" json:"c_type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	VideoTime     int64                  `protobuf:"varint,6,opt,name=video_time,json=videoTime,proto3" json:"video_time,omitempty"`
	HasVideoTime  bool                   `protobuf:"varint,7,opt,name=has_video_time,json=hasVideoTime,proto3" json:"has_video_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReq) Reset() {
	*x = MessageReq{}
	mi := &file_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReq) ProtoMessage() {}

func (x *MessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReq.ProtoReflect.Descriptor instead.
func (*MessageReq) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{2}
}

func (x *MessageReq) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessageReq) GetRecvId() string {
	if x != nil {
		return x.RecvId
	}
	return ""
}

func (x *MessageReq) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *MessageReq) GetCType() int32 {
	if x != nil {
		return x.CType
	}
	return 0
}

func (x *MessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageReq) GetVideoTime() int64 {
	if x != nil {
		return x.VideoTime
	}
	return 0
}

func (x *MessageReq) GetHasVideoTime() bool {
	if x != nil {
		return x.HasVideoTime
	}
	return false
}

type MessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId   string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Extra         string                 `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	SendTime      int64                  `protobuf:"varint,5,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_ws_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{3}
}

func (x *MessageAck) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessageAck) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MessageAck) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *MessageAck) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type MessageReadAckEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastReadSeq    int64                  `protobuf:"varint,3,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	ConvType       int32                  `protobuf:"varint,4,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`
	SenderId       string                 `protobuf:"bytes,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Avatar         string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageReadAckEvent) Reset() {
	*x = MessageReadAckEvent{}
	mi := &file_ws_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReadAckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReadAckEvent) ProtoMessage() {}

func (x *MessageReadAckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReadAckEvent.ProtoReflect.Descriptor instead.
func (*MessageReadAckEvent) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{4}
}

func (x *MessageReadAckEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MessageReadAckEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageReadAckEvent) GetLastReadSeq() int64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

func (x *MessageReadAckEvent) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *MessageReadAckEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageReadAckEvent) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type MessageEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SendId         string                 `protobuf:"bytes,3,opt,name=send_id,json=sendId,proto3" json:"send_id,omitempty"`
	RecvId         string                 `protobuf:"bytes,4,opt,name=recv_id,json=recvId,proto3" json:"recv_id,omitempty"`
	Seq            int64                  `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	ConvType       int32                  `protobuf:"varint,6,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`
	CType          int32                  `protobuf:"varint,7,opt,name=c_type,json=cType,proto3" json:"c_type,omitempty"`
	Content        string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	SendTime       int64                  `protobuf:"varint,9,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	SenderUsername string                 `protobuf:"bytes,10,opt,name=sender_username,json=senderUsername,proto3" json:"sender_username,omitempty"`
	ClientMsgId    string                 `protobuf:"bytes,11,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	HasVideoTime   bool                   `protobuf:"varint,12,opt,name=has_video_time,json=hasVideoTime,proto3" json:"has_video_time,omitempty"`
	VideoTime      int64                  `protobuf:"varint,13,opt,name=video_time,json=videoTime,proto3" json:"video_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_ws_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{5}
}

func (x *MessageEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageEvent) GetSendId() string {
	if x != nil {
		return x.SendId
	}
	return ""
}

func (x *MessageEvent) GetRecvId() string {
	if x != nil {
		return x.RecvId
	}
	return ""
}

func (x *MessageEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageEvent) GetConvType() int32 {
	if x != nil {
		return x.ConvType
	}
	return 0
}

func (x *MessageEvent) GetCType() int32 {
	if x != nil {
		return x.CType
	}
	return 0
}

func (x *MessageEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageEvent) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *MessageEvent) GetSenderUsername() string {
	if x != nil {
		return x.SenderUsername
	}
	return ""
}

func (x *MessageEvent) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessageEvent) GetHasVideoTime() bool {
	if x != nil {
		return x.HasVideoTime
	}
	return false
}

func (x *MessageEvent) GetVideoTime() int64 {
	if x != nil {
		return x.VideoTime
	}
	return 0
}

type WatchVideoControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	VideoId       string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	PositionMs    int64                  `protobuf:"varint,5,opt,name=position_ms,json=positionMs,proto3" json:"position_ms,omitempty"`
	DeltaMs       int64                  `protobuf:"varint,6,opt,name=delta_ms,json=deltaMs,proto3" json:"delta_ms,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	PlaybackRate  float64                `protobuf:"fixed64,8,opt,name=playback_rate,json=playbackRate,proto3" json:"playback_rate,omitempty"`
	ClientTimeMs  int64                  `protobuf:"varint,9,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchVideoControl) Reset() {
	*x = WatchVideoControl{}
	mi := &file_ws_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchVideoControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchVideoControl) ProtoMessage() {}

func (x *WatchVideoControl) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchVideoControl.ProtoReflect.Descriptor instead.
func (*WatchVideoControl) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{6}
}

func (x *WatchVideoControl) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *WatchVideoControl) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *WatchVideoControl) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *WatchVideoControl) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *WatchVideoControl) GetPositionMs() int64 {
	if x != nil {
		return x.PositionMs
	}
	return 0
}

func (x *WatchVideoControl) GetDeltaMs() int64 {
	if x != nil {
		return x.DeltaMs
	}
	return 0
}

func (x *WatchVideoControl) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *WatchVideoControl) GetPlaybackRate() float64 {
	if x != nil {
		return x.PlaybackRate
	}
	return 0
}

func (x *WatchVideoControl) GetClientTimeMs() int64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

type WatchVideoState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	VideoId       string                 `protobuf:"bytes,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	PositionMs    int64                  `protobuf:"varint,5,opt,name=position_ms,json=positionMs,proto3" json:"position_ms,omitempty"`
	DeltaMs       int64                  `protobuf:"varint,6,opt,name=delta_ms,json=deltaMs,proto3" json:"delta_ms,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	PlaybackRate  float64                `protobuf:"fixed64,8,opt,name=playback_rate,json=playbackRate,proto3" json:"playback_rate,omitempty"`
	IsPlaying     bool                   `protobuf:"varint,9,opt,name=is_playing,json=isPlaying,proto3" json:"is_playing,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAtMs   int64                  `protobuf:"varint,11,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	ClientTimeMs  int64                  `protobuf:"varint,12,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchVideoState) Reset() {
	*x = WatchVideoState{}
	mi := &file_ws_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchVideoState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchVideoState) ProtoMessage() {}

func (x *WatchVideoState) ProtoReflect() protoreflect.Message {
	mi := &file_ws_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchVideoState.ProtoReflect.Descriptor instead.
func (*WatchVideoState) Descriptor() ([]byte, []int) {
	return file_ws_proto_rawDescGZIP(), []int{7}
}

func (x *WatchVideoState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *WatchVideoState) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *WatchVideoState) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *WatchVideoState) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *WatchVideoState) GetPositionMs() int64 {
	if x != nil {
		return x.PositionMs
	}
	return 0
}

func (x *WatchVideoState) GetDeltaMs() int64 {
	if x != nil {
		return x.DeltaMs
	}
	return 0
}

func (x *WatchVideoState) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *WatchVideoState) GetPlaybackRate() float64 {
	if x != nil {
		return x.PlaybackRate
	}
	return 0
}

func (x *WatchVideoState) GetIsPlaying() bool {
	if x != nil {
		return x.IsPlaying
	}
	return false
}

func (x *WatchVideoState) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *WatchVideoState) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

func (x *WatchVideoState) GetClientTimeMs() int64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

var File_ws_proto protoreflect.FileDescriptor

const file_ws_proto_rawDesc = "" +
	"\n" +
	"\bws.proto\x12\x05im.ws\"-\n" +
	"\aWsFrame\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"}\n" +
	"\x11MessageReadAckReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\rlast_read_seq\x18\x02 \x01(\x03R\vlastReadSeq\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\"\xdc\x01\n" +
	"\n" +
	"MessageReq\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12\x17\n" +
	"\arecv_id\x18\x02 \x01(\tR\x06recvId\x12\x1b\n" +
	"\tconv_type\x18\x03 \x01(\x05R\bconvType\x12\x15\n" +
	"\x06c_type\x18\x04 \x01(\x05R\x05cType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"video_time\x18\x06 \x01(\x03R\tvideoTime\x12$\n" +
	"\x0ehas_video_time\x18\a \x01(\bR\fhasVideoTime\"\x9a\x01\n" +
	"\n" +
	"MessageAck\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05extra\x18\x04 \x01(\tR\x05extra\x12\x1b\n" +
	"\tsend_time\x18\x05 \x01(\x03R\bsendTime\"\xcd\x01\n" +
	"\x13MessageReadAckEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\"\n" +
	"\rlast_read_seq\x18\x03 \x01(\x03R\vlastReadSeq\x12\x1b\n" +
	"\tconv_type\x18\x04 \x01(\x05R\bconvType\x12\x1b\n" +
	"\tsender_id\x18\x05 \x01(\tR\bsenderId\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\"\x97\x03\n" +
	"\fMessageEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\asend_id\x18\x03 \x01(\tR\x06sendId\x12\x17\n" +
	"\arecv_id\x18\x04 \x01(\tR\x06recvId\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x03R\x03seq\x12\x1b\n" +
	"\tconv_type\x18\x06 \x01(\x05R\bconvType\x12\x15\n" +
	"\x06c_type\x18\a \x01(\x05R\x05cType\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1b\n" +
	"\tsend_time\x18\t \x01(\x03R\bsendTime\x12'\n" +
	"\x0fsender_username\x18\n" +
	" \x01(\tR\x0esenderUsername\x12\"\n" +
	"\rclient_msg_id\x18\v \x01(\tR\vclientMsgId\x12$\n" +
	"\x0ehas_video_time\x18\f \x01(\bR\fhasVideoTime\x12\x1d\n" +
	"\n" +
	"video_time\x18\r \x01(\x03R\tvideoTime\"\xa4\x02\n" +
	"\x11WatchVideoControl\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\x12\x1f\n" +
	"\vposition_ms\x18\x05 \x01(\x03R\n" +
	"positionMs\x12\x19\n" +
	"\bdelta_ms\x18\x06 \x01(\x03R\adeltaMs\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12#\n" +
	"\rplayback_rate\x18\b \x01(\x01R\fplaybackRate\x12$\n" +
	"\x0eclient_time_ms\x18\t \x01(\x03R\fclientTimeMs\"\x84\x03\n" +
	"\x0fWatchVideoState\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\tR\avideoId\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\x12\x1f\n" +
	"\vposition_ms\x18\x05 \x01(\x03R\n" +
	"positionMs\x12\x19\n" +
	"\bdelta_ms\x18\x06 \x01(\x03R\adeltaMs\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x12#\n" +
	"\rplayback_rate\x18\b \x01(\x01R\fplaybackRate\x12\x1d\n" +
	"\n" +
	"is_playing\x18\t \x01(\bR\tisPlaying\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\tR\tupdatedBy\x12\"\n" +
	"\rupdated_at_ms\x18\v \x01(\x03R\vupdatedAtMs\x12$\n" +
	"\x0eclient_time_ms\x18\f \x01(\x03R\fclientTimeMsB*Z(IM_backend/internal/transport/ws/pb;wspbb\x06proto3"

var (
	file_ws_proto_rawDescOnce sync.Once
	file_ws_proto_rawDescData []byte
)

func file_ws_proto_rawDescGZIP() []byte {
	file_ws_proto_rawDescOnce.Do(func() {
		file_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)))
	})
	return file_ws_proto_rawDescData
}

var file_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ws_proto_goTypes = []any{
	(*WsFrame)(nil),             // 0: im.ws.WsFrame
	(*MessageReadAckReq)(nil),   // 1: im.ws.MessageReadAckReq
	(*MessageReq)(nil),          // 2: im.ws.MessageReq
	(*MessageAck)(nil),          // 3: im.ws.MessageAck
	(*MessageReadAckEvent)(nil), // 4: im.ws.MessageReadAckEvent
	(*MessageEvent)(nil),        // 5: im.ws.MessageEvent
	(*WatchVideoControl)(nil),   // 6: im.ws.WatchVideoControl
	(*WatchVideoState)(nil),     // 7: im.ws.WatchVideoState
}
var file_ws_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ws_proto_init() }
func file_ws_proto_init() {
	if File_ws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_proto_rawDesc), len(file_ws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_proto_goTypes,
		DependencyIndexes: file_ws_proto_depIdxs,
		MessageInfos:      file_ws_proto_msgTypes,
	}.Build()
	File_ws_proto = out.File
	file_ws_proto_goTypes = nil
	file_ws_proto_depIdxs = nil
}
