app:
  name: "IMChat"
  version: "0.0.1"
  env: "development"
  machineId: 1
server:
  port: ":8081"
database:
  mysql:
    dsn: "user:123456@tcp(mysql:3306)/IMChat?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    dsn: "redis://redis:6379/0?dial_timeout=5s&read_timeout=3s&pool_size=50"
jwt:
  secret: "U2FsdGVkX19anQGSRtiUwgRLpWV333jI4xjlCF32dek="
  access_expire_hours: 0.25
  refresh_expire_hours: 168
ws:
  write_wait_seconds: 10
  pong_wait_seconds: 60
  max_message_size: 5120
  max_message_send_buffer_size: 256